### ISSUE TITLE
"controller describe-scope" command displays only scope-name

### ISSUE THREAD

**Issue by SomeshJoshi19** [pravega/pravega-tools#24] opened 2019-05-06 11:53 UTC
Pravega-cli command `controller describe-scope <scope-name>` returns only **scope-name** as output. It would have been better useful if this command could update total number of readers', writers' and containers' created, deleted and/or running any such details as the command is intent to describe some of the scope related specific information `controller describe-scope <scope-name>: Get the details of a given Scope`

Command: `controller describe-scope <scope-name>`
Output:
```
> controller describe-scope Scope
Successful REST request.
{"scopeName":"Scope"}
```

**Comment by RaulGracia** [comment] 2019-05-08 15:35
@SomeshJoshi19 this is not a bug, this is what the Controller REST API provides. If you desire to have more information, this is a feature request that may need to be discussed. And in fact, the place to discuss that may be the Pravega repo, as the this entails the REST call to provide a different output.

**Comment by RaulGracia** [comment] 2019-05-08 15:35
@SomeshJoshi19 this is not a bug, this is what the Controller REST API provides. If you desire to have more information, this is a feature request that may need to be discussed. And in fact, the place to discuss that may be the Pravega repo, as the this entails the REST call to provide a different output.

**Comment by RaulGracia** [comment] 2020-07-23 10:10
Closing as this is not a bug. Any further improvement of the `describe-scope` command should be done in the Pravega core repo.

**Closed as completed by RaulGracia** 2020-07-23 10:10 UTC
Labels: kind/enhancement, status/more-info-needed, area/pravega-cli
